language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

sudo: false

install:
  - pip install flake8 Flask

script:
  - flake8 --max-line-length=120 flask_defer.py && python test_flask_defer.py
